###
# Migrate data from an old geonode version to the latest one (2.4).
#
---

- name: "clear old layers"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM layers_layer"

- name: "clear old resourcebase"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM base_resourcebase"

- name: "clear old accounts"
  sudo: yes
  sudo_user: postgres
  command:  psql {{app_name}} -c "DELETE FROM account_account"

- name: "clear old accounts email"
  sudo: yes
  sudo_user: postgres
  command:  psql {{app_name}} -c "DELETE FROM account_emailaddress"

- name: "clear old groups"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM people_profile_groups"

- name: "clear old users"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM people_profile WHERE id > -1"

- name: "create view for bbox in legacy database"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "CREATE OR REPLACE VIEW maps_layer_bbox AS SELECT id, cast(bbox[1] as float) as bbox_x0, cast(bbox[2] as float) as bbox_y0, cast(bbox[3] as float) as bbox_x1, cast(bbox[4] as float) as bbox_y1 from (select id, string_to_array(replace(replace(replace(llbbox, ']',''), '[',''), ',',''), ' ') as bbox from maps_layer) as seq"

- name: "create new layers table view with bbox in legacy database"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "CREATE OR REPLACE VIEW augmented_maps_layer AS SELECT * FROM maps_layer INNER JOIN maps_layer_bbox USING (id) WHERE maps_layer_bbox.bbox_x0 > -181 and maps_layer_bbox.bbox_x1 < 181 and maps_layer_bbox.bbox_y0 > -91 and maps_layer_bbox.bbox_y1 < 90"

- name: "copy users"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c 'copy (select id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined from auth_user) to stdout with csv' | psql {{app_name}} -c 'copy people_profile (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) from stdin csv'

- name: "reset user sequence"
  sudo: yes
  sudo_user: postgres
  shell: psql {{app_name}} -c "SELECT setval(pg_get_serial_sequence('people_profile', 'id'), coalesce(max(id),0) + 1, false) FROM people_profile;"

- name: "get layers content type id needed for polymorphic"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "copy (select id from django_content_type where name like 'layer') to stdout with csv"
  register: layer_ctype

- name: "copy items to resourcebase"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "copy (select id, {{layer_ctype.stdout}}, uuid, owner_id, title, date, date_type, abstract, language, supplemental_information, 'EPSG:4326', 'csw_typename', 'csw_schema', 'csw_mdsource', 'csw_type', 'csw_wkt_geometry', false, 0, 0, false, true, bbox_x0, bbox_y0, bbox_x1, bbox_y1, typename from augmented_maps_layer) to stdout with csv" | psql {{app_name}} -c "copy base_resourcebase (id, polymorphic_ctype_id, uuid, owner_id, title, date, date_type, abstract, language, supplemental_information, srid, csw_typename, csw_schema, csw_mdsource, csw_type, csw_wkt_geometry, metadata_uploaded, popular_count, share_count, featured, is_published, bbox_x0, bbox_y0, bbox_x1, bbox_y1, detail_url) from stdin csv"

- name: "set detail_url as /layers/{{typename}}"
  sudo: yes
  sudo_user: postgres
  shell: psql {{app_name}} -c "UPDATE base_resourcebase SET detail_url = '/layers/'||detail_url;"

- name: "copy items to layer table"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c 'copy (select id, title, abstract, purpose, constraints_other, supplemental_information, distribution_description, data_quality_statement, workspace, store, "storeType", name, typename, name from augmented_maps_layer) to stdout with csv' | psql {{app_name}} -c 'copy layers_layer (resourcebase_ptr_id, title_en, abstract_en, purpose_en, constraints_other_en, supplemental_information_en, distribution_description_en, data_quality_statement_en, workspace, store, "storeType", name, typename, charset) from stdin csv'
