- hosts: localhost
  connection: local

  tasks:
    - name: Create multi-zone Postgres on RDS
      local_action:
        module: rds
        command: create
        instance_name: "{{ db_instance }}"
        region: "{{ db_region }}"
        db_engine: postgres
        instance_type: "{{ db_instance_type }}"
        multi_zone: "{{ db_multi_zone}}"
        publicly_accessible: "{{ db_publicly_accessible }}"
        size: "{{ db_size }}"
        maint_window: "{{ db_maint_window }}"
        backup_retention: "{{ db_backup_retention }}"
        backup_window: "{{ db_backup_window }}"
        license_model: "{{ db_license_model }}"
        db_name: "{{ db_name }}"
        username: "{{ db_user }}"
        password: "{{ db_password }}"
        tags:
          environment: testing
          application: worldmap
          owner: ariel

    - name: Get facts about postgres instance.
      local_action:
        module: rds
        command: facts
        instance_name: "{{ db_instance }}"
        register: postgres_facts

    - name: Ensure postgresql postgis extension is created
      shell: "PGPASSWORD='{{db_password}}' psql -h {{db_host}} -d {{db_name}} -U {{db_user}}  -c 'CREATE EXTENSION postgis;'"
      register: psql_result
      failed_when: >
         psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
      changed_when: "psql_result.rc == 0"


#      - name: Delete postgres rds instance, but create a snapshot before doing so
#        local_action:
#          module: rds
#          command: delete
#          instance_name: postgres
#          snapshot: postgres_snapshot
