###
# Installs nginx 
#
---
- name: ensure apt cache is up to date
  apt: update_cache=yes 
  become: yes

- name: ensure apache packages are installed
  apt:
    pkg: ['apache2', 'libapache2-mod-wsgi']
    state: present
  become: yes

- name: write apache configuration
  template: src=geonode.conf.j2 dest=/etc/apache2/sites-available/geonode.conf
  become: yes

- name: enable proxy apache module
  shell: a2enmod proxy
  become: yes
  when: apache

- name: enable proxy_http apache module
  shell: a2enmod proxy_http
  become: yes
  when: apache

- name: enable headers apache module
  shell: a2enmod headers
  become: yes
  when: apache

- name: enable geonode apache module
  shell: a2ensite geonode
  become: yes
  when: apache
  notify:
    - restart apache
