###
# Installs nginx
#
---
- name: ensure apt cache is up to date
  apt: update_cache=yes 
  become: yes

- name: ensure nginx is installed
  apt: name=nginx
  become: yes

- name: nginx site configuration
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: adding robots.txt
  become: yes
  template:
    src: robots.txt.j2
    dest: /var/www/html/robots.txt
