###
# Install uwsgi and configure it in emperor mode.
#
---

- name: update apt cache
  apt: update_cache=yes
  become: yes

- name: install uwsgi emperor
  apt: name={{item}}
  become: yes
  with_items:
    - uwsgi-emperor
    - uwsgi-plugin-python

- name: write default vassals configuration file
  template: src=vassals-default.skel.j2 dest=/etc/uwsgi-emperor/vassals/vassals-default.skel
  become: yes
  notify:
    - restart uwsgi
